
name: 'trangdang_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'trangdang_dbt_project'

model-paths: ["models"]
test-paths: ["tests"]

target-path: "target" 
log-path: "logs"
packages-install-path: "dbt_packages"
clean-targets:      
  - "target"
  - "dbt_packages"


models:
  trangdang_dbt_project:
    analytics:
      +materialized: table

    staging: 
      +materialized: view
      +schema: staging
